--@test: len - length of a string - JSON
CREATE STREAM INPUT (ID BIGINT KEY, S STRING, B BYTES) WITH (kafka_topic='input_topic',value_format='JSON');
CREATE STREAM OUTPUT AS SELECT ID, LEN(S) AS S, LEN(B) AS B FROM INPUT;
INSERT INTO `INPUT` (ID, S, B) VALUES (1, 'ABC', 'YWJj');
INSERT INTO `INPUT` (ID, S, B) VALUES (2, '', '');
INSERT INTO `INPUT` (ID, S, B) VALUES (3, NULL, NULL);
ASSERT VALUES `OUTPUT` (ID, S, B) VALUES (1, 3, 3);
ASSERT VALUES `OUTPUT` (ID, S, B) VALUES (2, 0, 0);
ASSERT VALUES `OUTPUT` (ID, S, B) VALUES (3, NULL, NULL);

