--@test: arrayjoin - join flat arrays with primitive ksqldb types and default delimiter
CREATE STREAM TEST (ID STRING KEY, BOOLEANARRAY ARRAY<BOOLEAN>, INTARRAY ARRAY<INT>, BIGINTARRAY ARRAY<BIGINT>, DOUBLEARRAY ARRAY<DOUBLE>, DECIMALARRAY ARRAY<DECIMAL(5,2)>, STRINGARRAY ARRAY<STRING>) WITH (kafka_topic='test_topic', value_format='JSON');
CREATE STREAM OUTPUT AS SELECT ID, ARRAY_JOIN(BOOLEANARRAY), ARRAY_JOIN(INTARRAY), ARRAY_JOIN(BIGINTARRAY), ARRAY_JOIN(DOUBLEARRAY), ARRAY_JOIN(DECIMALARRAY), ARRAY_JOIN(STRINGARRAY) FROM TEST;
INSERT INTO `TEST` (ID, BOOLEANARRAY, INTARRAY, BIGINTARRAY, DOUBLEARRAY, DECIMALARRAY, STRINGARRAY) VALUES ('1', ARRAY[true, NULL, false], ARRAY[1, 23, -42, 0], ARRAY[-4294967297, 8589934592], ARRAY[1.23, -23.42, 0.0], ARRAY[123.45, 987.65], ARRAY['Hello', 'From', '', 'Ksqldb', 'Udf']);
ASSERT VALUES `OUTPUT` (ID, KSQL_COL_0, KSQL_COL_1, KSQL_COL_2, KSQL_COL_3, KSQL_COL_4, KSQL_COL_5) VALUES ('1', 'true,null,false', '1,23,-42,0', '-4294967297,8589934592', '1.23,-23.42,0.0', '123.45,987.65', 'Hello,From,,Ksqldb,Udf');

--@test: arrayjoin - join flat arrays with primitive ksqldb types and custom delimiters
CREATE STREAM TEST (ID STRING KEY, BOOLEANARRAY ARRAY<BOOLEAN>, INTARRAY ARRAY<INT>, BIGINTARRAY ARRAY<BIGINT>, DOUBLEARRAY ARRAY<DOUBLE>, DECIMALARRAY ARRAY<DECIMAL(5,2)>, STRINGARRAY ARRAY<STRING>) WITH (kafka_topic='test_topic', value_format='JSON');
CREATE STREAM OUTPUT AS SELECT ID, ARRAY_JOIN(BOOLEANARRAY,'|'), ARRAY_JOIN(INTARRAY,'?'), ARRAY_JOIN(BIGINTARRAY,';'), ARRAY_JOIN(DOUBLEARRAY,' '), ARRAY_JOIN(DECIMALARRAY,'#'), ARRAY_JOIN(STRINGARRAY,'_') FROM TEST;
INSERT INTO `TEST` (ID, BOOLEANARRAY, INTARRAY, BIGINTARRAY, DOUBLEARRAY, DECIMALARRAY, STRINGARRAY) VALUES ('1', ARRAY[true, NULL, false], ARRAY[1, 23, -42, 0], ARRAY[-4294967297, 8589934592], ARRAY[1.23, -23.42, 0.0], ARRAY[123.45, 987.65], ARRAY['Hello', 'From', '', 'Ksqldb', 'Udf']);
ASSERT VALUES `OUTPUT` (ID, KSQL_COL_0, KSQL_COL_1, KSQL_COL_2, KSQL_COL_3, KSQL_COL_4, KSQL_COL_5) VALUES ('1', 'true|null|false', '1?23?-42?0', '-4294967297;8589934592', '1.23 -23.42 0.0', '123.45#987.65', 'Hello_From__Ksqldb_Udf');

--@test: arrayjoin - join flat arrays with primitive ksqldb types and empty or null delimiter
CREATE STREAM TEST (ID STRING KEY, BOOLEANARRAY ARRAY<BOOLEAN>, INTARRAY ARRAY<INT>, BIGINTARRAY ARRAY<BIGINT>, DOUBLEARRAY ARRAY<DOUBLE>, DECIMALARRAY ARRAY<DECIMAL(5,2)>, STRINGARRAY ARRAY<STRING>) WITH (kafka_topic='test_topic', value_format='JSON');
CREATE STREAM OUTPUT AS SELECT ID, ARRAY_JOIN(BOOLEANARRAY,''), ARRAY_JOIN(INTARRAY,null), ARRAY_JOIN(BIGINTARRAY,''), ARRAY_JOIN(DOUBLEARRAY,null), ARRAY_JOIN(DECIMALARRAY,''), ARRAY_JOIN(STRINGARRAY,null) FROM TEST;
INSERT INTO `TEST` (ID, BOOLEANARRAY, INTARRAY, BIGINTARRAY, DOUBLEARRAY, DECIMALARRAY, STRINGARRAY) VALUES ('1', ARRAY[true, NULL, false], ARRAY[1, 23, -42, 0], ARRAY[-4294967297, 8589934592], ARRAY[1.23, -23.42, 0.0], ARRAY[123.45, 987.65], ARRAY['Hello', 'From', '', 'Ksqldb', 'Udf']);
ASSERT VALUES `OUTPUT` (ID, KSQL_COL_0, KSQL_COL_1, KSQL_COL_2, KSQL_COL_3, KSQL_COL_4, KSQL_COL_5) VALUES ('1', 'truenullfalse', '123-420', '-42949672978589934592', '1.23-23.420.0', '123.45987.65', 'HelloFromKsqldbUdf');

