# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Build documentation in the docs/ directory with Sphinx 
#sphinx:
#  configuration: docs/conf.py

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Required
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

python:
 install:
   - requirements: docs/requirements.txt

# Add redirects to content on docs.confluent

redirects:
  - type: page
    from_url: 'https://docs.ksqldb.io/en/latest/how-to-guides/convert-changelog-to-table/'
    to_url: 'https://docs.confluent.io/platform/current/ksqldb/overview.html'
  - type: page
    from_url: 'https://docs.ksqldb.io/en/latest/how-to-guides/test-an-app/'
    to_url: 'https://docs.confluent.io/platform/current/ksqldb/overview.html'