DROP STREAM clickstream;
DROP TABLE events_per_min;
DROP TABLE events_per_min_ts;
DROP TABLE events_per_min_max_avg;
DROP TABLE events_per_min_max_avg_ts;
DROP TABLE clickstream_codes;
DROP TABLE clickstream_codes_ts;
DROP TABLE pages_per_min;
DROP TABLE pages_per_min_ts;
DROP TABLE ERRORS_PER_MIN_ALERT;
DROP TABLE ERRORS_PER_MIN_ALERT_TS;
DROP TABLE ERRORS_PER_MIN;
DROP TABLE ERRORS_PER_MIN_TS;
DROP STREAM ENRICHED_ERROR_CODES;
DROP TABLE ENRICHED_ERROR_CODES_COUNT;
DROP STREAM ENRICHED_ERROR_CODES_TS;
DROP TABLE WEB_USERS;
DROP STREAM customer_clickstream;
DROP STREAM platinum_customers_with_errors;
DROP STREAM platinum_errors;
DROP TABLE PLATINUM_ERRORS_PER_5_MIN;
DROP TABLE platinum_page_errors_per_5_min;
DROP STREAM USER_CLICKSTREAM;
DROP TABLE USER_IP_ACTIVITY;
DROP TABLE USER_IP_ACTIVITY_TS;
DROP TABLE CLICK_USER_SESSIONS;
DROP TABLE CLICK_USER_SESSIONS_TS;
DROP TABLE PER_USER_KBYTES;
DROP TABLE PER_USER_KBYTES_TS;
DROP TABLE MALICIOUS_USER_SESSIONS;
--
--terminate 1;
--terminate 2;
--terminate 3;
--terminate 4;
--terminate 5;
--terminate 6;
--terminate 7;
--terminate 8;
--terminate 9;



