/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    implementation(project(":ksqldb-common"))
    implementation(project(":ksqldb-serde"))
    implementation(project(":ksqldb-execution"))
    implementation("org.apache.kafka:connect-api:7.4.0-27-ccs")
    implementation("org.apache.kafka:connect-runtime:7.4.0-27-ccs")
    testImplementation(project(":ksqldb-common"))
    testImplementation(project(":ksqldb-test-util"))
}

description = "ksqldb-streams"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
