/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    implementation(project(":ksqldb-engine"))
    implementation("io.confluent:kafka-connect-avro-converter:7.4.0-103")
    implementation("io.confluent.avro:avro-random-generator:0.2.2")
    testImplementation(project(":ksqldb-common"))
    testImplementation(project(":ksqldb-test-util"))
}

description = "ksqldb-examples"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
