/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    api(project(":ksqldb-engine"))
    implementation("io.confluent:kafka-connect-avro-converter:7.4.0-103")
    api("io.confluent.avro:avro-random-generator:0.2.2")
    testImplementation(project(mapOf("path" to ":ksqldb-common", "configuration" to "testOutput")))
    testImplementation(project(":ksqldb-test-util"))
}

description = "ksqldb-examples"

tasks.withType<JavaCompile> {
    val compilerArgs = options.compilerArgs
    compilerArgs.addAll(listOf("-Xlint:all,-serial"))
    // TODO: handle compile.warnings-flag
}

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

// TODO: build archives matching maven-assembly-plugin & 3 .xml files