/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    implementation(project(":ksqldb-rest-app"))
    implementation(project(":ksqldb-cli"))
    implementation(project(":ksqldb-functional-tests"))
    implementation(project(":ksqldb-tools"))
    api("org.apache.kafka:kafka-clients:7.4.0-27-ccs")
    implementation("org.apache.kafka:kafka_2.13:7.4.0-27-ccs")
    implementation("org.hamcrest:hamcrest-all:1.3")
    implementation("junit:junit:4.13.2")
}

description = "ksqldb-docker"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

// TODO: generate directory structure equiv to maven-assembly-plugin & package.xml
// TODO: generate Docker image equiv to Dockerfile & dockerfile-maven-plugin