import com.palantir.gradle.docker.DockerExtension

/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("io.confluent.ksql.java-conventions")
    id("com.palantir.docker") version "0.34.0"
}

dependencies {
    implementation(project(":ksqldb-rest-app"))
    implementation(project(":ksqldb-cli"))
    implementation(project(":ksqldb-functional-tests"))
    implementation(project(":ksqldb-tools"))
    api("org.apache.kafka:kafka-clients:7.4.0-27-ccs")
    implementation("org.apache.kafka:kafka_2.13:7.4.0-27-ccs")
    implementation("org.hamcrest:hamcrest-all:1.3")
    implementation("junit:junit:4.13.2")
}

description = "ksqldb-docker"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

// generate directory structure equiv to maven-assembly-plugin & package.xml

val makeAssembly by tasks.registering(Copy::class) {
    into(layout.buildDirectory.dir("package"))

    into("share/doc/ksqldb-docker") {
        from(rootProject.rootDir)
        include("version.txt", "COPYRIGHT*")
    }
    into("etc/ksqldb-docker") {
        from(File(rootProject.rootDir, "config"))
    }
    into("bin") {
        from(File(rootProject.rootDir, "bin"))
//        include("/*")
    }
    into("bin") {
        from( "src/include")
        include("docker/*")
    }
    into("share/java/ksqldb-docker") {
        from(sourceSets.main.get().runtimeClasspath)
        // TODO: exclude io.confluent:common-* & com.google.guava:guava
    }
}

// generate Docker image equiv to Dockerfile & dockerfile-maven-plugin
configure<DockerExtension> {
    name = "confluentinc/${project.name}"
    buildArgs(mapOf(
        "DOCKER_UPSTREAM_REGISTRY" to "",
        "DOCKER_UPSTREAM_TAG" to "latest",
        "ARTIFACT_ID" to project.name,
        "PROJECT_VERSION" to project.version.toString(),
    ))
    files(makeAssembly.get().outputs)
    tag("server", "confluentinc/ksqldb-server:local.build")
    tag("cli", "confluentinc/ksqldb-cli:local.build")
}
