/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    implementation(project(":ksqldb-rest-app"))
    testImplementation(project(":ksqldb-test-util"))
    testImplementation("org.reactivestreams:reactive-streams-tck:1.0.3")
    testImplementation("org.testng:testng:6.11")
}

description = "ksqldb-api-reactive-streams-tck"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

tasks.named<Test>("test") {
    useTestNG()
}
