/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
    id("com.github.davidmc24.gradle.plugin.avro") version "1.3.0"
}

dependencies {
    api(project(":ksqldb-common"))
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.2.2")
    implementation(project(":ksqldb-engine"))
    implementation("org.apache.httpcomponents.client5:httpclient5:5.0.3")
    testImplementation(project(":ksqldb-test-util"))
    testImplementation("com.github.tomakehurst:wiremock-jre8:2.24.0")
}

description = "ksqldb-version-metrics-client"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
