/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    implementation(project(":ksqldb-common"))
    implementation(project(":ksqldb-metastore"))
    implementation("io.airlift:slice:0.29")
    implementation("org.antlr:antlr4-runtime:4.9.2")
    implementation("org.apache.commons:commons-lang3:3.5")
    implementation("org.apache.commons:commons-text:1.8")
    implementation("com.approvaltests:approvaltests:9.5.0")
    testImplementation(project(":ksqldb-metastore"))
    testImplementation(project(":ksqldb-common"))
    testImplementation(project(":ksqldb-test-util"))
}

description = "ksqldb-parser"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
