#!/usr/bin/env bash

#
# Copyright 2019 Confluent Inc.
#
# Licensed under the Confluent Community License (the "License"); you may not use
# this file except in compliance with the License.  You may obtain a copy of the
# License at
#
# http://www.confluent.io/confluent-community-license
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#


echo "===> Configuring ksqlDB..."
dub template "/etc/ksql/connect.properties.template" "/etc/ksql/connect.properties"

# KSQL_CONNECT_GROUP_ID is a required configuration for running embedded connect,
# so we can proxy it to check whether or not to start an embedded connect worker
if ! [[ -z "${KSQL_CONNECT_GROUP_ID}" ]]; then
  echo "===> Configuring Embedded Connect"
  /usr/bin/docker/configure

  echo "===> Enabling Embedded Connect"
  export KSQL_KSQL_CONNECT_WORKER_CONFIG="/etc/ksql/connect.properties"
fi

dub template "/etc/ksql/ksqldb-server.properties.template" "/etc/ksql/ksqldb-server.properties"

echo "===> Launching ksqlDB Server..."
/usr/bin/ksql-server-start /etc/ksql/ksqldb-server.properties