#
# Copyright 2025 Confluent Inc.
#
# Licensed under the Confluent Community License (the "License"); you may not use
# this file except in compliance with the License.  You may obtain a copy of the
# License at
#
# http://www.confluent.io/confluent-community-license
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#

Configuration:
  Properties:
    Property:
      - name: ksql.log.dir
        value: ${sys:ksql.log.dir}
  Appenders:
    TimestampLogFileAppender:
      type: io.confluent.ksql.util.TimestampLogFileAppender
      name: defaultFile
      fileName: ${ksql.log.dir}/ksql-cli/cli-%timestamp.log
      filePattern: ${ksql.log.dir}/ksql-cli/cli-%d{yyyy-MM-dd}-%i.log
      PatternLayout:
        pattern: "[%d] %p %m (%c:%L)%n"
      ImmediateFlush: true
  Loggers:
    Root:
      level: WARN
      AppenderRef:
        - ref: defaultFile