--@test: datestring - date to string
CREATE STREAM TEST (ID bigint KEY, START_DATE int, DATE_FORMAT varchar) WITH (kafka_topic='test_topic', value_format='JSON');
CREATE STREAM DATE_STREAM AS select ID, datetostring(START_DATE, DATE_FORMAT) as CUSTOM_FORMATTED_START_DATE from test;
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (1, 17662, 'yyyy-MM-dd');
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (2, 18027, 'dd/MM/yyyy');
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (3, 18993, 'dd-MMM-yyyy');
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (4, 0, 'dd-MM-yyyy');
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (5, -1, 'dd-MM-yyyy''Sophia''');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (1, '2018-05-11');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (2, '11/05/2019');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (3, '01-Jan-2022');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (4, '01-01-1970');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (5, '31-12-1969Sophia');

