--@test: format-date - date to string
CREATE STREAM TEST (ID bigint KEY, START_DATE DATE, DATE_FORMAT varchar) WITH (kafka_topic='test_topic', value_format='JSON');
CREATE STREAM DATE_STREAM AS select ID, format_date(START_DATE, DATE_FORMAT) as CUSTOM_FORMATTED_START_DATE from test;
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (1, '2018-05-11', 'yyyy-MM-dd');
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (2, '2019-05-11', 'dd/MM/yyyy');
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (3, '2022-01-01', 'dd-MMM-yyyy');
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (4, '1970-01-01', 'dd-MM-yyyy');
INSERT INTO `TEST` (ID, START_DATE, DATE_FORMAT) VALUES (5, '1969-12-31', 'dd-MM-yyyy''Sophia''');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (1, '2018-05-11');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (2, '11/05/2019');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (3, '01-Jan-2022');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (4, '01-01-1970');
ASSERT VALUES `DATE_STREAM` (ID, CUSTOM_FORMATTED_START_DATE) VALUES (5, '31-12-1969Sophia');

