--@test: format-time - time to string
CREATE STREAM TEST (ID bigint KEY, START_TIME time, DATE_FORMAT varchar) WITH (kafka_topic='test_topic', value_format='JSON');
CREATE STREAM TIME_STREAM AS select ID, format_time(START_TIME, DATE_FORMAT) as CUSTOM_FORMATTED_START_TIME from test;
INSERT INTO `TEST` (ID, START_TIME, DATE_FORMAT) VALUES (1, '00:01:05', 'HH_mm_ss_SSS');
INSERT INTO `TEST` (ID, START_TIME, DATE_FORMAT) VALUES (2, '00:20:34', 'HHmmss''AAAAA''');
INSERT INTO `TEST` (ID, START_TIME, DATE_FORMAT) VALUES (3, '00:00', 'HH:mm:ss');
INSERT INTO `TEST` (ID, DATE_FORMAT) VALUES (5, 'HH:mm:ss');
ASSERT VALUES `TIME_STREAM` (ID, CUSTOM_FORMATTED_START_TIME) VALUES (1, '00_01_05_000');
ASSERT VALUES `TIME_STREAM` (ID, CUSTOM_FORMATTED_START_TIME) VALUES (2, '002034AAAAA');
ASSERT VALUES `TIME_STREAM` (ID, CUSTOM_FORMATTED_START_TIME) VALUES (3, '00:00:00');
ASSERT VALUES `TIME_STREAM` (ID, CUSTOM_FORMATTED_START_TIME) VALUES (5, NULL);

