--@test: test-custom-udaf - test_udaf group by
CREATE STREAM TEST (ID BIGINT KEY, NAME varchar, VALUE integer) WITH (kafka_topic='test_topic',value_format='DELIMITED');
CREATE TABLE S2 as SELECT id, AS_VALUE(ID) AS ID2, test_udaf(value) FROM test group by id;
INSERT INTO `TEST` (ID, NAME, VALUE) VALUES (0, 'zero', -2147483647);
INSERT INTO `TEST` (ID, NAME, VALUE) VALUES (0, '100', 5);
INSERT INTO `TEST` (ID, NAME, VALUE) VALUES (100, '100', 100);
INSERT INTO `TEST` (ID, NAME, VALUE) VALUES (100, '100', 6);
INSERT INTO `TEST` (ID, NAME, VALUE) VALUES (100, '100', 300);
INSERT INTO `TEST` (ID, NAME, VALUE) VALUES (0, 'zero', 2000);
INSERT INTO `TEST` (ID, NAME, VALUE) VALUES (0, '100', 100);
ASSERT VALUES `S2` (ID, ID2, KSQL_COL_0) VALUES (0, 0, -2147483647);
ASSERT VALUES `S2` (ID, ID2, KSQL_COL_0) VALUES (0, 0, -2147483642);
ASSERT VALUES `S2` (ID, ID2, KSQL_COL_0) VALUES (100, 100, 100);
ASSERT VALUES `S2` (ID, ID2, KSQL_COL_0) VALUES (100, 100, 106);
ASSERT VALUES `S2` (ID, ID2, KSQL_COL_0) VALUES (100, 100, 406);
ASSERT VALUES `S2` (ID, ID2, KSQL_COL_0) VALUES (0, 0, -2147481642);
ASSERT VALUES `S2` (ID, ID2, KSQL_COL_0) VALUES (0, 0, -2147481542);

--@test: test-custom-udaf - test_udaf on a table
CREATE TABLE TEST (ID BIGINT PRIMARY KEY, NAME varchar, REGION string) WITH (kafka_topic='test_topic', value_format='DELIMITED');
CREATE TABLE SUM_ID_BY_REGION AS SELECT REGION, test_udaf(id) FROM TEST GROUP BY REGION;
INSERT INTO `TEST` (ID, NAME, REGION) VALUES (0, 'alice', 'east');
INSERT INTO `TEST` (ID, NAME, REGION) VALUES (1, 'bob', 'east');
INSERT INTO `TEST` (ID, NAME, REGION) VALUES (2, 'carol', 'west');
INSERT INTO `TEST` (ID, NAME, REGION) VALUES (3, 'dave', 'west');
INSERT INTO `TEST` (ID, NAME, REGION) VALUES (1, 'bob', 'west');
INSERT INTO `TEST` (ID) VALUES (1);
ASSERT VALUES `SUM_ID_BY_REGION` (REGION, KSQL_COL_0) VALUES ('east', 0);
ASSERT VALUES `SUM_ID_BY_REGION` (REGION, KSQL_COL_0) VALUES ('east', 1);
ASSERT VALUES `SUM_ID_BY_REGION` (REGION, KSQL_COL_0) VALUES ('west', 2);
ASSERT VALUES `SUM_ID_BY_REGION` (REGION, KSQL_COL_0) VALUES ('west', 5);
ASSERT VALUES `SUM_ID_BY_REGION` (REGION, KSQL_COL_0) VALUES ('east', 0);
ASSERT VALUES `SUM_ID_BY_REGION` (REGION, KSQL_COL_0) VALUES ('west', 6);
ASSERT VALUES `SUM_ID_BY_REGION` (REGION, KSQL_COL_0) VALUES ('west', 5);

--@test: test-custom-udaf - test_udaf with struct
CREATE STREAM TEST (K BIGINT KEY, id VARCHAR, val STRUCT<A INT, B INT>) WITH (kafka_topic='test_topic', value_format='JSON');
CREATE TABLE RESULT AS SELECT ID, test_udaf(val) as result FROM TEST GROUP BY ID;
INSERT INTO `TEST` (K, id, val) VALUES (0, '0', STRUCT(A:=1, B:=2));
INSERT INTO `TEST` (K, id, val) VALUES (0, '0', STRUCT(A:=2, B:=3));
INSERT INTO `TEST` (K, id, val) VALUES (1, '1', STRUCT(A:=1, B:=0));
ASSERT VALUES `RESULT` (ID, RESULT) VALUES ('0', STRUCT(A:=1, B:=2));
ASSERT VALUES `RESULT` (ID, RESULT) VALUES ('0', STRUCT(A:=3, B:=5));
ASSERT VALUES `RESULT` (ID, RESULT) VALUES ('1', STRUCT(A:=1, B:=0));

