#! /usr/bin/env bash

BASE_DIR=$(dirname "$0")

KSQL_SERVER="$BASE_DIR/../target/ksql-server"

if ! [ -f "$KSQL_SERVER" ]; then
  echo 1>&2 "Server script not found. Perhaps you forgot to build?"
  exit 1
fi

"$KSQL_SERVER" "$@"
