#!/usr/bin/env bash
#
# Copyright 2017 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o nounset \
    -o errexit \
    -o verbose \
    -o xtrace

echo "===> Check if Kafka is healthy ..."

if [[ -n "${KSQL_SECURITY_PROTOCOL-}" ]] && [[ $KSQL_SECURITY_PROTOCOL != "PLAINTEXT" ]]
then
    cub kafka-ready \
        "${KSQL_CUB_KAFKA_MIN_BROKERS:-1}" \
        "${KSQL_CUB_KAFKA_TIMEOUT:-40}" \
        -b "${KSQL_BOOTSTRAP_SERVERS}" \
        --config /etc/"${COMPONENT}"/"${COMPONENT}".properties
else
    if [[ -n "${KSQL_ZOOKEEPER_CONNECT-}" ]]
    then
        cub kafka-ready \
            "${KSQL_CUB_KAFKA_MIN_BROKERS:-1}" \
            "${KSQL_CUB_KAFKA_TIMEOUT:-40}" \
            -z "$KSQL_ZOOKEEPER_CONNECT"
    elif [[ -n "${KSQL_BOOTSTRAP_SERVERS-}" ]]
    then
        cub kafka-ready \
            "${KSQL_CUB_KAFKA_MIN_BROKERS:-1}" \
            "${KSQL_CUB_KAFKA_TIMEOUT:-40}" \
            -b "${KSQL_BOOTSTRAP_SERVERS}"
    fi
fi
