/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    // maven {
    //     url = uri("https://confluent.jfrog.io/confluent/maven-releases-stabilization/")
    // }

    maven {
        url = uri("https://confluent.jfrog.io//confluent/maven-public/")
        credentials {
            username = project.properties["mavenUsername"].toString()
            password = project.properties["mavenPassword"].toString()
        }
    }

    maven {
        url = uri("https://packages.confluent.io/maven/")
    }

    maven {
        url = uri("https://s3-us-west-2.amazonaws.com/confluent-snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("io.confluent:common-utils:7.4.0-106")
    implementation("org.slf4j:slf4j-reload4j:1.7.36")
    implementation("io.confluent:logredactor:1.0.10")
    implementation("io.confluent:common-utils:7.4.0-106")
    compileOnly("io.confluent:assembly-plugin-boilerplate:7.4.0-106")
    compileOnly("io.confluent:assembly-plugin-boilerplate:7.4.0-106")
    compileOnly("io.confluent:assembly-plugin-boilerplate:7.4.0-106")
}

group = "io.confluent.ksql"
version = "7.4.0-0"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Test>().configureEach {
    maxParallelForks = (Runtime.getRuntime().availableProcessors() / 2).takeIf { it > 0 } ?: 1
}