/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    api("org.apache.curator:curator-test:5.2.0")
    api("org.apache.kafka:kafka_2.13:7.4.0-27-ccs")
    api("org.apache.kafka:kafka_2.13:7.4.0-27-ccs:test")
    api("org.apache.kafka:kafka-clients:7.4.0-27-ccs")
    api("org.apache.kafka:kafka-clients:7.4.0-27-ccs:test")
    api("com.google.guava:guava:30.1.1-jre")
    api("com.github.spotbugs:spotbugs-annotations:4.7.1")
    api("junit:junit:4.13.2")
    api("org.hamcrest:hamcrest-all:1.3")
    api("org.easymock:easymock:4.3")
    api("org.mockito:mockito-inline:4.6.1")
    api("org.mockito:mockito-core:4.6.1")
    api("com.google.guava:guava-testlib:30.1.1-jre")
}

description = "ksqldb-test-util"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
