/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("io.confluent:kafka-connect-avro-converter:7.4.0-103")
    implementation("io.confluent:common-logging:7.4.0-106")
    implementation("org.apache.kafka:connect-api:7.4.0-27-ccs")
    implementation("org.apache.kafka:kafka-streams:7.4.0-27-ccs")
    implementation("org.apache.avro:avro:1.11.0")
    implementation("com.github.spotbugs:spotbugs-annotations:4.7.1")
    implementation("org.apache.commons:commons-lang3:3.5")
    implementation("io.vertx:vertx-core:4.3.2")
    implementation("io.vertx:vertx-codegen:4.3.2")
    implementation("org.reactivestreams:reactive-streams:1.0.3")
    implementation(project(":ksqldb-udf"))
    testImplementation(project(":ksqldb-test-util"))
    testImplementation("com.google.guava:guava-testlib:30.1.1-jre")
}

description = "ksqldb-common"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
