/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    implementation("javax.inject:javax.inject:1")
    implementation("net.java.dev.jna:jna:4.4.0")
    implementation("com.github.rvesse:airline:2.6.0")
    implementation("com.github.spotbugs:spotbugs-annotations:4.7.1")
    implementation(project(":ksqldb-common"))
    implementation(project(":ksqldb-parser"))
    implementation(project(":ksqldb-api-client"))
    implementation(project(":ksqldb-execution")) // TODO: find transitive source
    testImplementation(project(":ksqldb-test-util"))
    testImplementation(project(":ksqldb-rest-app"))
    testImplementation(project(mapOf("path" to ":ksqldb-rest-app", "configuration" to "testOutput")))
    testImplementation(project(mapOf("path" to ":ksqldb-engine", "configuration" to "testOutput")))
}

description = "ksqldb-tools"

tasks.withType<JavaCompile> {
    val compilerArgs = options.compilerArgs
    compilerArgs.addAll(listOf("-Xlint:all,-serial"))
    // TODO: handle compile.warnings-flag
}

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)

// TODO: generate archives equiv to maven-assembly-plugin & 3 .xml files and single
