/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.confluent.ksql.java-conventions")
}

dependencies {
    implementation("com.google.errorprone:error_prone_annotations:2.2.0")
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("com.github.spotbugs:spotbugs-annotations:4.7.1")
    testImplementation(project(":ksqldb-test-util"))
}

description = "ksqldb-udf"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
