// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SampleProtoB.proto

package io.confluent.ksql.serde.protobuf;

public final class SampleProtoBOuterClass {
  private SampleProtoBOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SampleProtoBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtocolBuffers.SampleProtoB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double double_field = 1;</code>
     */
    double getDoubleField();

    /**
     * <code>float float_field = 2;</code>
     */
    float getFloatField();

    /**
     * <code>int32 int32_field = 3;</code>
     */
    int getInt32Field();

    /**
     * <code>int64 int64_field = 4;</code>
     */
    long getInt64Field();

    /**
     * <code>uint32 uint32_field = 5;</code>
     */
    int getUint32Field();

    /**
     * <code>uint64 uint64_field = 6;</code>
     */
    long getUint64Field();

    /**
     * <code>sint32 sint32_field = 7;</code>
     */
    int getSint32Field();

    /**
     * <code>sint64 sint64_field = 8;</code>
     */
    long getSint64Field();

    /**
     * <code>fixed32 fixed32_field = 9;</code>
     */
    int getFixed32Field();

    /**
     * <code>fixed64 fixed64_field = 10;</code>
     */
    long getFixed64Field();

    /**
     * <code>sfixed32 sfixed32_field = 11;</code>
     */
    int getSfixed32Field();

    /**
     * <code>sfixed64 sfixed64_field = 12;</code>
     */
    long getSfixed64Field();

    /**
     * <code>bool bool_field = 13;</code>
     */
    boolean getBoolField();

    /**
     * <code>string string_field = 14;</code>
     */
    String getStringField();
    /**
     * <code>string string_field = 14;</code>
     */
    com.google.protobuf.ByteString
        getStringFieldBytes();

    /**
     * <code>bytes bytes_field = 15;</code>
     */
    com.google.protobuf.ByteString getBytesField();

    /**
     * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
     */
    int getCustomEnumFieldValue();
    /**
     * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
     */
    SampleProtoB.CustomEnum getCustomEnumField();

    /**
     * <pre>
     * Repeated (Array)
     * </pre>
     *
     * <code>repeated string array_field = 17;</code>
     */
    java.util.List<String>
        getArrayFieldList();
    /**
     * <pre>
     * Repeated (Array)
     * </pre>
     *
     * <code>repeated string array_field = 17;</code>
     */
    int getArrayFieldCount();
    /**
     * <pre>
     * Repeated (Array)
     * </pre>
     *
     * <code>repeated string array_field = 17;</code>
     */
    String getArrayField(int index);
    /**
     * <pre>
     * Repeated (Array)
     * </pre>
     *
     * <code>repeated string array_field = 17;</code>
     */
    com.google.protobuf.ByteString
        getArrayFieldBytes(int index);

    /**
     * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
     */
    boolean hasEmbeddedField();
    /**
     * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
     */
    SampleProtoB.Embedded getEmbeddedField();
    /**
     * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
     */
    SampleProtoB.EmbeddedOrBuilder getEmbeddedFieldOrBuilder();

    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */
    int getMapFieldCount();
    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */
    boolean containsMapField(
      String key);
    /**
     * Use {@link #getMapFieldMap()} instead.
     */
    @Deprecated
    java.util.Map<String, Integer>
    getMapField();
    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */
    java.util.Map<String, Integer>
    getMapFieldMap();
    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */

    int getMapFieldOrDefault(
      String key,
      int defaultValue);
    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */

    int getMapFieldOrThrow(
      String key);
  }
  /**
   * <pre>
   * Sample ProtocolBuffer that defines all field types.
   * </pre>
   *
   * Protobuf type {@code ProtocolBuffers.SampleProtoB}
   */
  public  static final class SampleProtoB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtocolBuffers.SampleProtoB)
      SampleProtoBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SampleProtoB.newBuilder() to construct.
    private SampleProtoB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SampleProtoB() {
      doubleField_ = 0D;
      floatField_ = 0F;
      int32Field_ = 0;
      int64Field_ = 0L;
      uint32Field_ = 0;
      uint64Field_ = 0L;
      sint32Field_ = 0;
      sint64Field_ = 0L;
      fixed32Field_ = 0;
      fixed64Field_ = 0L;
      sfixed32Field_ = 0;
      sfixed64Field_ = 0L;
      boolField_ = false;
      stringField_ = "";
      bytesField_ = com.google.protobuf.ByteString.EMPTY;
      customEnumField_ = 0;
      arrayField_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SampleProtoB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              doubleField_ = input.readDouble();
              break;
            }
            case 21: {

              floatField_ = input.readFloat();
              break;
            }
            case 24: {

              int32Field_ = input.readInt32();
              break;
            }
            case 32: {

              int64Field_ = input.readInt64();
              break;
            }
            case 40: {

              uint32Field_ = input.readUInt32();
              break;
            }
            case 48: {

              uint64Field_ = input.readUInt64();
              break;
            }
            case 56: {

              sint32Field_ = input.readSInt32();
              break;
            }
            case 64: {

              sint64Field_ = input.readSInt64();
              break;
            }
            case 77: {

              fixed32Field_ = input.readFixed32();
              break;
            }
            case 81: {

              fixed64Field_ = input.readFixed64();
              break;
            }
            case 93: {

              sfixed32Field_ = input.readSFixed32();
              break;
            }
            case 97: {

              sfixed64Field_ = input.readSFixed64();
              break;
            }
            case 104: {

              boolField_ = input.readBool();
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              stringField_ = s;
              break;
            }
            case 122: {

              bytesField_ = input.readBytes();
              break;
            }
            case 128: {
              int rawValue = input.readEnum();

              customEnumField_ = rawValue;
              break;
            }
            case 138: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00010000) == 0x00010000)) {
                arrayField_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00010000;
              }
              arrayField_.add(s);
              break;
            }
            case 146: {
              Embedded.Builder subBuilder = null;
              if (embeddedField_ != null) {
                subBuilder = embeddedField_.toBuilder();
              }
              embeddedField_ = input.readMessage(Embedded.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(embeddedField_);
                embeddedField_ = subBuilder.buildPartial();
              }

              break;
            }
            case 154: {
              if (!((mutable_bitField0_ & 0x00040000) == 0x00040000)) {
                mapField_ = com.google.protobuf.MapField.newMapField(
                    MapFieldDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00040000;
              }
              com.google.protobuf.MapEntry<String, Integer>
              mapField__ = input.readMessage(
                  MapFieldDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mapField_.getMutableMap().put(
                  mapField__.getKey(), mapField__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00010000) == 0x00010000)) {
          arrayField_ = arrayField_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 19:
          return internalGetMapField();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SampleProtoB.class, Builder.class);
    }

    /**
     * <pre>
     * Enumeration Type
     * </pre>
     *
     * Protobuf enum {@code ProtocolBuffers.SampleProtoB.CustomEnum}
     */
    public enum CustomEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>A = 0;</code>
       */
      A(0),
      /**
       * <code>B = 1;</code>
       */
      B(1),
      /**
       * <code>C = 3;</code>
       */
      C(3),
      /**
       * <code>D = 4;</code>
       */
      D(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>A = 0;</code>
       */
      public static final int A_VALUE = 0;
      /**
       * <code>B = 1;</code>
       */
      public static final int B_VALUE = 1;
      /**
       * <code>C = 3;</code>
       */
      public static final int C_VALUE = 3;
      /**
       * <code>D = 4;</code>
       */
      public static final int D_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static CustomEnum valueOf(int value) {
        return forNumber(value);
      }

      public static CustomEnum forNumber(int value) {
        switch (value) {
          case 0: return A;
          case 1: return B;
          case 3: return C;
          case 4: return D;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CustomEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CustomEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CustomEnum>() {
              public CustomEnum findValueByNumber(int number) {
                return CustomEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SampleProtoB.getDescriptor().getEnumTypes().get(0);
      }

      private static final CustomEnum[] VALUES = values();

      public static CustomEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CustomEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ProtocolBuffers.SampleProtoB.CustomEnum)
    }

    public interface EmbeddedOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ProtocolBuffers.SampleProtoB.Embedded)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * <pre>
     * Embedded Object
     * </pre>
     *
     * Protobuf type {@code ProtocolBuffers.SampleProtoB.Embedded}
     */
    public  static final class Embedded extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ProtocolBuffers.SampleProtoB.Embedded)
        EmbeddedOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Embedded.newBuilder() to construct.
      private Embedded(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Embedded() {
        name_ = "";
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Embedded(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_Embedded_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_Embedded_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Embedded.class, Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Embedded)) {
          return super.equals(obj);
        }
        Embedded other = (Embedded) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Embedded parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Embedded parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Embedded parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Embedded parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Embedded parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Embedded parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Embedded parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Embedded parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Embedded parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Embedded parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Embedded parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Embedded parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Embedded prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * Embedded Object
       * </pre>
       *
       * Protobuf type {@code ProtocolBuffers.SampleProtoB.Embedded}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ProtocolBuffers.SampleProtoB.Embedded)
          EmbeddedOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_Embedded_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_Embedded_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Embedded.class, Builder.class);
        }

        // Construct using io.confluent.ksql.serde.protobuf.SampleProtoBOuterClass.SampleProtoB.Embedded.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          name_ = "";

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_Embedded_descriptor;
        }

        @Override
        public Embedded getDefaultInstanceForType() {
          return Embedded.getDefaultInstance();
        }

        @Override
        public Embedded build() {
          Embedded result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Embedded buildPartial() {
          Embedded result = new Embedded(this);
          result.name_ = name_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Embedded) {
            return mergeFrom((Embedded)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Embedded other) {
          if (other == Embedded.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Embedded parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Embedded) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public String getName() {
          Object ref = name_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ProtocolBuffers.SampleProtoB.Embedded)
      }

      // @@protoc_insertion_point(class_scope:ProtocolBuffers.SampleProtoB.Embedded)
      private static final Embedded DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Embedded();
      }

      public static Embedded getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Embedded>
          PARSER = new com.google.protobuf.AbstractParser<Embedded>() {
        @Override
        public Embedded parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Embedded(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Embedded> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Embedded> getParserForType() {
        return PARSER;
      }

      @Override
      public Embedded getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int DOUBLE_FIELD_FIELD_NUMBER = 1;
    private double doubleField_;
    /**
     * <code>double double_field = 1;</code>
     */
    public double getDoubleField() {
      return doubleField_;
    }

    public static final int FLOAT_FIELD_FIELD_NUMBER = 2;
    private float floatField_;
    /**
     * <code>float float_field = 2;</code>
     */
    public float getFloatField() {
      return floatField_;
    }

    public static final int INT32_FIELD_FIELD_NUMBER = 3;
    private int int32Field_;
    /**
     * <code>int32 int32_field = 3;</code>
     */
    public int getInt32Field() {
      return int32Field_;
    }

    public static final int INT64_FIELD_FIELD_NUMBER = 4;
    private long int64Field_;
    /**
     * <code>int64 int64_field = 4;</code>
     */
    public long getInt64Field() {
      return int64Field_;
    }

    public static final int UINT32_FIELD_FIELD_NUMBER = 5;
    private int uint32Field_;
    /**
     * <code>uint32 uint32_field = 5;</code>
     */
    public int getUint32Field() {
      return uint32Field_;
    }

    public static final int UINT64_FIELD_FIELD_NUMBER = 6;
    private long uint64Field_;
    /**
     * <code>uint64 uint64_field = 6;</code>
     */
    public long getUint64Field() {
      return uint64Field_;
    }

    public static final int SINT32_FIELD_FIELD_NUMBER = 7;
    private int sint32Field_;
    /**
     * <code>sint32 sint32_field = 7;</code>
     */
    public int getSint32Field() {
      return sint32Field_;
    }

    public static final int SINT64_FIELD_FIELD_NUMBER = 8;
    private long sint64Field_;
    /**
     * <code>sint64 sint64_field = 8;</code>
     */
    public long getSint64Field() {
      return sint64Field_;
    }

    public static final int FIXED32_FIELD_FIELD_NUMBER = 9;
    private int fixed32Field_;
    /**
     * <code>fixed32 fixed32_field = 9;</code>
     */
    public int getFixed32Field() {
      return fixed32Field_;
    }

    public static final int FIXED64_FIELD_FIELD_NUMBER = 10;
    private long fixed64Field_;
    /**
     * <code>fixed64 fixed64_field = 10;</code>
     */
    public long getFixed64Field() {
      return fixed64Field_;
    }

    public static final int SFIXED32_FIELD_FIELD_NUMBER = 11;
    private int sfixed32Field_;
    /**
     * <code>sfixed32 sfixed32_field = 11;</code>
     */
    public int getSfixed32Field() {
      return sfixed32Field_;
    }

    public static final int SFIXED64_FIELD_FIELD_NUMBER = 12;
    private long sfixed64Field_;
    /**
     * <code>sfixed64 sfixed64_field = 12;</code>
     */
    public long getSfixed64Field() {
      return sfixed64Field_;
    }

    public static final int BOOL_FIELD_FIELD_NUMBER = 13;
    private boolean boolField_;
    /**
     * <code>bool bool_field = 13;</code>
     */
    public boolean getBoolField() {
      return boolField_;
    }

    public static final int STRING_FIELD_FIELD_NUMBER = 14;
    private volatile Object stringField_;
    /**
     * <code>string string_field = 14;</code>
     */
    public String getStringField() {
      Object ref = stringField_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stringField_ = s;
        return s;
      }
    }
    /**
     * <code>string string_field = 14;</code>
     */
    public com.google.protobuf.ByteString
        getStringFieldBytes() {
      Object ref = stringField_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stringField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTES_FIELD_FIELD_NUMBER = 15;
    private com.google.protobuf.ByteString bytesField_;
    /**
     * <code>bytes bytes_field = 15;</code>
     */
    public com.google.protobuf.ByteString getBytesField() {
      return bytesField_;
    }

    public static final int CUSTOM_ENUM_FIELD_FIELD_NUMBER = 16;
    private int customEnumField_;
    /**
     * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
     */
    public int getCustomEnumFieldValue() {
      return customEnumField_;
    }
    /**
     * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
     */
    public CustomEnum getCustomEnumField() {
      @SuppressWarnings("deprecation")
      CustomEnum result = CustomEnum.valueOf(customEnumField_);
      return result == null ? CustomEnum.UNRECOGNIZED : result;
    }

    public static final int ARRAY_FIELD_FIELD_NUMBER = 17;
    private com.google.protobuf.LazyStringList arrayField_;
    /**
     * <pre>
     * Repeated (Array)
     * </pre>
     *
     * <code>repeated string array_field = 17;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getArrayFieldList() {
      return arrayField_;
    }
    /**
     * <pre>
     * Repeated (Array)
     * </pre>
     *
     * <code>repeated string array_field = 17;</code>
     */
    public int getArrayFieldCount() {
      return arrayField_.size();
    }
    /**
     * <pre>
     * Repeated (Array)
     * </pre>
     *
     * <code>repeated string array_field = 17;</code>
     */
    public String getArrayField(int index) {
      return arrayField_.get(index);
    }
    /**
     * <pre>
     * Repeated (Array)
     * </pre>
     *
     * <code>repeated string array_field = 17;</code>
     */
    public com.google.protobuf.ByteString
        getArrayFieldBytes(int index) {
      return arrayField_.getByteString(index);
    }

    public static final int EMBEDDED_FIELD_FIELD_NUMBER = 18;
    private Embedded embeddedField_;
    /**
     * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
     */
    public boolean hasEmbeddedField() {
      return embeddedField_ != null;
    }
    /**
     * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
     */
    public Embedded getEmbeddedField() {
      return embeddedField_ == null ? Embedded.getDefaultInstance() : embeddedField_;
    }
    /**
     * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
     */
    public EmbeddedOrBuilder getEmbeddedFieldOrBuilder() {
      return getEmbeddedField();
    }

    public static final int MAP_FIELD_FIELD_NUMBER = 19;
    private static final class MapFieldDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, Integer>newDefaultInstance(
                  SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_MapFieldEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        String, Integer> mapField_;
    private com.google.protobuf.MapField<String, Integer>
    internalGetMapField() {
      if (mapField_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapFieldDefaultEntryHolder.defaultEntry);
      }
      return mapField_;
    }

    public int getMapFieldCount() {
      return internalGetMapField().getMap().size();
    }
    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */

    public boolean containsMapField(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetMapField().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapFieldMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, Integer> getMapField() {
      return getMapFieldMap();
    }
    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */

    public java.util.Map<String, Integer> getMapFieldMap() {
      return internalGetMapField().getMap();
    }
    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */

    public int getMapFieldOrDefault(
        String key,
        int defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Integer> map =
          internalGetMapField().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Map field
     * </pre>
     *
     * <code>map&lt;string, int32&gt; map_field = 19;</code>
     */

    public int getMapFieldOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Integer> map =
          internalGetMapField().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (doubleField_ != 0D) {
        output.writeDouble(1, doubleField_);
      }
      if (floatField_ != 0F) {
        output.writeFloat(2, floatField_);
      }
      if (int32Field_ != 0) {
        output.writeInt32(3, int32Field_);
      }
      if (int64Field_ != 0L) {
        output.writeInt64(4, int64Field_);
      }
      if (uint32Field_ != 0) {
        output.writeUInt32(5, uint32Field_);
      }
      if (uint64Field_ != 0L) {
        output.writeUInt64(6, uint64Field_);
      }
      if (sint32Field_ != 0) {
        output.writeSInt32(7, sint32Field_);
      }
      if (sint64Field_ != 0L) {
        output.writeSInt64(8, sint64Field_);
      }
      if (fixed32Field_ != 0) {
        output.writeFixed32(9, fixed32Field_);
      }
      if (fixed64Field_ != 0L) {
        output.writeFixed64(10, fixed64Field_);
      }
      if (sfixed32Field_ != 0) {
        output.writeSFixed32(11, sfixed32Field_);
      }
      if (sfixed64Field_ != 0L) {
        output.writeSFixed64(12, sfixed64Field_);
      }
      if (boolField_ != false) {
        output.writeBool(13, boolField_);
      }
      if (!getStringFieldBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, stringField_);
      }
      if (!bytesField_.isEmpty()) {
        output.writeBytes(15, bytesField_);
      }
      if (customEnumField_ != CustomEnum.A.getNumber()) {
        output.writeEnum(16, customEnumField_);
      }
      for (int i = 0; i < arrayField_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, arrayField_.getRaw(i));
      }
      if (embeddedField_ != null) {
        output.writeMessage(18, getEmbeddedField());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMapField(),
          MapFieldDefaultEntryHolder.defaultEntry,
          19);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (doubleField_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, doubleField_);
      }
      if (floatField_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, floatField_);
      }
      if (int32Field_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, int32Field_);
      }
      if (int64Field_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, int64Field_);
      }
      if (uint32Field_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, uint32Field_);
      }
      if (uint64Field_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, uint64Field_);
      }
      if (sint32Field_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(7, sint32Field_);
      }
      if (sint64Field_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(8, sint64Field_);
      }
      if (fixed32Field_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(9, fixed32Field_);
      }
      if (fixed64Field_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(10, fixed64Field_);
      }
      if (sfixed32Field_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(11, sfixed32Field_);
      }
      if (sfixed64Field_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(12, sfixed64Field_);
      }
      if (boolField_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, boolField_);
      }
      if (!getStringFieldBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, stringField_);
      }
      if (!bytesField_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, bytesField_);
      }
      if (customEnumField_ != CustomEnum.A.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(16, customEnumField_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arrayField_.size(); i++) {
          dataSize += computeStringSizeNoTag(arrayField_.getRaw(i));
        }
        size += dataSize;
        size += 2 * getArrayFieldList().size();
      }
      if (embeddedField_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(18, getEmbeddedField());
      }
      for (java.util.Map.Entry<String, Integer> entry
           : internalGetMapField().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, Integer>
        mapField__ = MapFieldDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(19, mapField__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SampleProtoB)) {
        return super.equals(obj);
      }
      SampleProtoB other = (SampleProtoB) obj;

      boolean result = true;
      result = result && (
          Double.doubleToLongBits(getDoubleField())
          == Double.doubleToLongBits(
              other.getDoubleField()));
      result = result && (
          Float.floatToIntBits(getFloatField())
          == Float.floatToIntBits(
              other.getFloatField()));
      result = result && (getInt32Field()
          == other.getInt32Field());
      result = result && (getInt64Field()
          == other.getInt64Field());
      result = result && (getUint32Field()
          == other.getUint32Field());
      result = result && (getUint64Field()
          == other.getUint64Field());
      result = result && (getSint32Field()
          == other.getSint32Field());
      result = result && (getSint64Field()
          == other.getSint64Field());
      result = result && (getFixed32Field()
          == other.getFixed32Field());
      result = result && (getFixed64Field()
          == other.getFixed64Field());
      result = result && (getSfixed32Field()
          == other.getSfixed32Field());
      result = result && (getSfixed64Field()
          == other.getSfixed64Field());
      result = result && (getBoolField()
          == other.getBoolField());
      result = result && getStringField()
          .equals(other.getStringField());
      result = result && getBytesField()
          .equals(other.getBytesField());
      result = result && customEnumField_ == other.customEnumField_;
      result = result && getArrayFieldList()
          .equals(other.getArrayFieldList());
      result = result && (hasEmbeddedField() == other.hasEmbeddedField());
      if (hasEmbeddedField()) {
        result = result && getEmbeddedField()
            .equals(other.getEmbeddedField());
      }
      result = result && internalGetMapField().equals(
          other.internalGetMapField());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOUBLE_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDoubleField()));
      hash = (37 * hash) + FLOAT_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getFloatField());
      hash = (37 * hash) + INT32_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getInt32Field();
      hash = (37 * hash) + INT64_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInt64Field());
      hash = (37 * hash) + UINT32_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getUint32Field();
      hash = (37 * hash) + UINT64_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUint64Field());
      hash = (37 * hash) + SINT32_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getSint32Field();
      hash = (37 * hash) + SINT64_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSint64Field());
      hash = (37 * hash) + FIXED32_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getFixed32Field();
      hash = (37 * hash) + FIXED64_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFixed64Field());
      hash = (37 * hash) + SFIXED32_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getSfixed32Field();
      hash = (37 * hash) + SFIXED64_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSfixed64Field());
      hash = (37 * hash) + BOOL_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBoolField());
      hash = (37 * hash) + STRING_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getStringField().hashCode();
      hash = (37 * hash) + BYTES_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getBytesField().hashCode();
      hash = (37 * hash) + CUSTOM_ENUM_FIELD_FIELD_NUMBER;
      hash = (53 * hash) + customEnumField_;
      if (getArrayFieldCount() > 0) {
        hash = (37 * hash) + ARRAY_FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getArrayFieldList().hashCode();
      }
      if (hasEmbeddedField()) {
        hash = (37 * hash) + EMBEDDED_FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getEmbeddedField().hashCode();
      }
      if (!internalGetMapField().getMap().isEmpty()) {
        hash = (37 * hash) + MAP_FIELD_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMapField().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SampleProtoB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SampleProtoB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SampleProtoB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SampleProtoB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SampleProtoB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SampleProtoB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SampleProtoB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SampleProtoB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SampleProtoB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SampleProtoB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SampleProtoB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SampleProtoB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SampleProtoB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Sample ProtocolBuffer that defines all field types.
     * </pre>
     *
     * Protobuf type {@code ProtocolBuffers.SampleProtoB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtocolBuffers.SampleProtoB)
        SampleProtoBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 19:
            return internalGetMapField();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 19:
            return internalGetMutableMapField();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SampleProtoB.class, Builder.class);
      }

      // Construct using io.confluent.ksql.serde.protobuf.SampleProtoBOuterClass.SampleProtoB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        doubleField_ = 0D;

        floatField_ = 0F;

        int32Field_ = 0;

        int64Field_ = 0L;

        uint32Field_ = 0;

        uint64Field_ = 0L;

        sint32Field_ = 0;

        sint64Field_ = 0L;

        fixed32Field_ = 0;

        fixed64Field_ = 0L;

        sfixed32Field_ = 0;

        sfixed64Field_ = 0L;

        boolField_ = false;

        stringField_ = "";

        bytesField_ = com.google.protobuf.ByteString.EMPTY;

        customEnumField_ = 0;

        arrayField_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00010000);
        if (embeddedFieldBuilder_ == null) {
          embeddedField_ = null;
        } else {
          embeddedField_ = null;
          embeddedFieldBuilder_ = null;
        }
        internalGetMutableMapField().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SampleProtoBOuterClass.internal_static_ProtocolBuffers_SampleProtoB_descriptor;
      }

      @Override
      public SampleProtoB getDefaultInstanceForType() {
        return SampleProtoB.getDefaultInstance();
      }

      @Override
      public SampleProtoB build() {
        SampleProtoB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SampleProtoB buildPartial() {
        SampleProtoB result = new SampleProtoB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.doubleField_ = doubleField_;
        result.floatField_ = floatField_;
        result.int32Field_ = int32Field_;
        result.int64Field_ = int64Field_;
        result.uint32Field_ = uint32Field_;
        result.uint64Field_ = uint64Field_;
        result.sint32Field_ = sint32Field_;
        result.sint64Field_ = sint64Field_;
        result.fixed32Field_ = fixed32Field_;
        result.fixed64Field_ = fixed64Field_;
        result.sfixed32Field_ = sfixed32Field_;
        result.sfixed64Field_ = sfixed64Field_;
        result.boolField_ = boolField_;
        result.stringField_ = stringField_;
        result.bytesField_ = bytesField_;
        result.customEnumField_ = customEnumField_;
        if (((bitField0_ & 0x00010000) == 0x00010000)) {
          arrayField_ = arrayField_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00010000);
        }
        result.arrayField_ = arrayField_;
        if (embeddedFieldBuilder_ == null) {
          result.embeddedField_ = embeddedField_;
        } else {
          result.embeddedField_ = embeddedFieldBuilder_.build();
        }
        result.mapField_ = internalGetMapField();
        result.mapField_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SampleProtoB) {
          return mergeFrom((SampleProtoB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SampleProtoB other) {
        if (other == SampleProtoB.getDefaultInstance()) return this;
        if (other.getDoubleField() != 0D) {
          setDoubleField(other.getDoubleField());
        }
        if (other.getFloatField() != 0F) {
          setFloatField(other.getFloatField());
        }
        if (other.getInt32Field() != 0) {
          setInt32Field(other.getInt32Field());
        }
        if (other.getInt64Field() != 0L) {
          setInt64Field(other.getInt64Field());
        }
        if (other.getUint32Field() != 0) {
          setUint32Field(other.getUint32Field());
        }
        if (other.getUint64Field() != 0L) {
          setUint64Field(other.getUint64Field());
        }
        if (other.getSint32Field() != 0) {
          setSint32Field(other.getSint32Field());
        }
        if (other.getSint64Field() != 0L) {
          setSint64Field(other.getSint64Field());
        }
        if (other.getFixed32Field() != 0) {
          setFixed32Field(other.getFixed32Field());
        }
        if (other.getFixed64Field() != 0L) {
          setFixed64Field(other.getFixed64Field());
        }
        if (other.getSfixed32Field() != 0) {
          setSfixed32Field(other.getSfixed32Field());
        }
        if (other.getSfixed64Field() != 0L) {
          setSfixed64Field(other.getSfixed64Field());
        }
        if (other.getBoolField() != false) {
          setBoolField(other.getBoolField());
        }
        if (!other.getStringField().isEmpty()) {
          stringField_ = other.stringField_;
          onChanged();
        }
        if (other.getBytesField() != com.google.protobuf.ByteString.EMPTY) {
          setBytesField(other.getBytesField());
        }
        if (other.customEnumField_ != 0) {
          setCustomEnumFieldValue(other.getCustomEnumFieldValue());
        }
        if (!other.arrayField_.isEmpty()) {
          if (arrayField_.isEmpty()) {
            arrayField_ = other.arrayField_;
            bitField0_ = (bitField0_ & ~0x00010000);
          } else {
            ensureArrayFieldIsMutable();
            arrayField_.addAll(other.arrayField_);
          }
          onChanged();
        }
        if (other.hasEmbeddedField()) {
          mergeEmbeddedField(other.getEmbeddedField());
        }
        internalGetMutableMapField().mergeFrom(
            other.internalGetMapField());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SampleProtoB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SampleProtoB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double doubleField_ ;
      /**
       * <code>double double_field = 1;</code>
       */
      public double getDoubleField() {
        return doubleField_;
      }
      /**
       * <code>double double_field = 1;</code>
       */
      public Builder setDoubleField(double value) {
        
        doubleField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double double_field = 1;</code>
       */
      public Builder clearDoubleField() {
        
        doubleField_ = 0D;
        onChanged();
        return this;
      }

      private float floatField_ ;
      /**
       * <code>float float_field = 2;</code>
       */
      public float getFloatField() {
        return floatField_;
      }
      /**
       * <code>float float_field = 2;</code>
       */
      public Builder setFloatField(float value) {
        
        floatField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float float_field = 2;</code>
       */
      public Builder clearFloatField() {
        
        floatField_ = 0F;
        onChanged();
        return this;
      }

      private int int32Field_ ;
      /**
       * <code>int32 int32_field = 3;</code>
       */
      public int getInt32Field() {
        return int32Field_;
      }
      /**
       * <code>int32 int32_field = 3;</code>
       */
      public Builder setInt32Field(int value) {
        
        int32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int32_field = 3;</code>
       */
      public Builder clearInt32Field() {
        
        int32Field_ = 0;
        onChanged();
        return this;
      }

      private long int64Field_ ;
      /**
       * <code>int64 int64_field = 4;</code>
       */
      public long getInt64Field() {
        return int64Field_;
      }
      /**
       * <code>int64 int64_field = 4;</code>
       */
      public Builder setInt64Field(long value) {
        
        int64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 int64_field = 4;</code>
       */
      public Builder clearInt64Field() {
        
        int64Field_ = 0L;
        onChanged();
        return this;
      }

      private int uint32Field_ ;
      /**
       * <code>uint32 uint32_field = 5;</code>
       */
      public int getUint32Field() {
        return uint32Field_;
      }
      /**
       * <code>uint32 uint32_field = 5;</code>
       */
      public Builder setUint32Field(int value) {
        
        uint32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uint32_field = 5;</code>
       */
      public Builder clearUint32Field() {
        
        uint32Field_ = 0;
        onChanged();
        return this;
      }

      private long uint64Field_ ;
      /**
       * <code>uint64 uint64_field = 6;</code>
       */
      public long getUint64Field() {
        return uint64Field_;
      }
      /**
       * <code>uint64 uint64_field = 6;</code>
       */
      public Builder setUint64Field(long value) {
        
        uint64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 uint64_field = 6;</code>
       */
      public Builder clearUint64Field() {
        
        uint64Field_ = 0L;
        onChanged();
        return this;
      }

      private int sint32Field_ ;
      /**
       * <code>sint32 sint32_field = 7;</code>
       */
      public int getSint32Field() {
        return sint32Field_;
      }
      /**
       * <code>sint32 sint32_field = 7;</code>
       */
      public Builder setSint32Field(int value) {
        
        sint32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 sint32_field = 7;</code>
       */
      public Builder clearSint32Field() {
        
        sint32Field_ = 0;
        onChanged();
        return this;
      }

      private long sint64Field_ ;
      /**
       * <code>sint64 sint64_field = 8;</code>
       */
      public long getSint64Field() {
        return sint64Field_;
      }
      /**
       * <code>sint64 sint64_field = 8;</code>
       */
      public Builder setSint64Field(long value) {
        
        sint64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 sint64_field = 8;</code>
       */
      public Builder clearSint64Field() {
        
        sint64Field_ = 0L;
        onChanged();
        return this;
      }

      private int fixed32Field_ ;
      /**
       * <code>fixed32 fixed32_field = 9;</code>
       */
      public int getFixed32Field() {
        return fixed32Field_;
      }
      /**
       * <code>fixed32 fixed32_field = 9;</code>
       */
      public Builder setFixed32Field(int value) {
        
        fixed32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 fixed32_field = 9;</code>
       */
      public Builder clearFixed32Field() {
        
        fixed32Field_ = 0;
        onChanged();
        return this;
      }

      private long fixed64Field_ ;
      /**
       * <code>fixed64 fixed64_field = 10;</code>
       */
      public long getFixed64Field() {
        return fixed64Field_;
      }
      /**
       * <code>fixed64 fixed64_field = 10;</code>
       */
      public Builder setFixed64Field(long value) {
        
        fixed64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 fixed64_field = 10;</code>
       */
      public Builder clearFixed64Field() {
        
        fixed64Field_ = 0L;
        onChanged();
        return this;
      }

      private int sfixed32Field_ ;
      /**
       * <code>sfixed32 sfixed32_field = 11;</code>
       */
      public int getSfixed32Field() {
        return sfixed32Field_;
      }
      /**
       * <code>sfixed32 sfixed32_field = 11;</code>
       */
      public Builder setSfixed32Field(int value) {
        
        sfixed32Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 sfixed32_field = 11;</code>
       */
      public Builder clearSfixed32Field() {
        
        sfixed32Field_ = 0;
        onChanged();
        return this;
      }

      private long sfixed64Field_ ;
      /**
       * <code>sfixed64 sfixed64_field = 12;</code>
       */
      public long getSfixed64Field() {
        return sfixed64Field_;
      }
      /**
       * <code>sfixed64 sfixed64_field = 12;</code>
       */
      public Builder setSfixed64Field(long value) {
        
        sfixed64Field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed64 sfixed64_field = 12;</code>
       */
      public Builder clearSfixed64Field() {
        
        sfixed64Field_ = 0L;
        onChanged();
        return this;
      }

      private boolean boolField_ ;
      /**
       * <code>bool bool_field = 13;</code>
       */
      public boolean getBoolField() {
        return boolField_;
      }
      /**
       * <code>bool bool_field = 13;</code>
       */
      public Builder setBoolField(boolean value) {
        
        boolField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool bool_field = 13;</code>
       */
      public Builder clearBoolField() {
        
        boolField_ = false;
        onChanged();
        return this;
      }

      private Object stringField_ = "";
      /**
       * <code>string string_field = 14;</code>
       */
      public String getStringField() {
        Object ref = stringField_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          stringField_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string string_field = 14;</code>
       */
      public com.google.protobuf.ByteString
          getStringFieldBytes() {
        Object ref = stringField_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          stringField_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string_field = 14;</code>
       */
      public Builder setStringField(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string_field = 14;</code>
       */
      public Builder clearStringField() {
        
        stringField_ = getDefaultInstance().getStringField();
        onChanged();
        return this;
      }
      /**
       * <code>string string_field = 14;</code>
       */
      public Builder setStringFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringField_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesField_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes_field = 15;</code>
       */
      public com.google.protobuf.ByteString getBytesField() {
        return bytesField_;
      }
      /**
       * <code>bytes bytes_field = 15;</code>
       */
      public Builder setBytesField(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytesField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes_field = 15;</code>
       */
      public Builder clearBytesField() {
        
        bytesField_ = getDefaultInstance().getBytesField();
        onChanged();
        return this;
      }

      private int customEnumField_ = 0;
      /**
       * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
       */
      public int getCustomEnumFieldValue() {
        return customEnumField_;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
       */
      public Builder setCustomEnumFieldValue(int value) {
        customEnumField_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
       */
      public CustomEnum getCustomEnumField() {
        @SuppressWarnings("deprecation")
        CustomEnum result = CustomEnum.valueOf(customEnumField_);
        return result == null ? CustomEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
       */
      public Builder setCustomEnumField(CustomEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        customEnumField_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.CustomEnum custom_enum_field = 16;</code>
       */
      public Builder clearCustomEnumField() {
        
        customEnumField_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList arrayField_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArrayFieldIsMutable() {
        if (!((bitField0_ & 0x00010000) == 0x00010000)) {
          arrayField_ = new com.google.protobuf.LazyStringArrayList(arrayField_);
          bitField0_ |= 0x00010000;
         }
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getArrayFieldList() {
        return arrayField_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public int getArrayFieldCount() {
        return arrayField_.size();
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public String getArrayField(int index) {
        return arrayField_.get(index);
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public com.google.protobuf.ByteString
          getArrayFieldBytes(int index) {
        return arrayField_.getByteString(index);
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public Builder setArrayField(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArrayFieldIsMutable();
        arrayField_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public Builder addArrayField(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArrayFieldIsMutable();
        arrayField_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public Builder addAllArrayField(
          Iterable<String> values) {
        ensureArrayFieldIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arrayField_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public Builder clearArrayField() {
        arrayField_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00010000);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Repeated (Array)
       * </pre>
       *
       * <code>repeated string array_field = 17;</code>
       */
      public Builder addArrayFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureArrayFieldIsMutable();
        arrayField_.add(value);
        onChanged();
        return this;
      }

      private Embedded embeddedField_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Embedded, Embedded.Builder, EmbeddedOrBuilder> embeddedFieldBuilder_;
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      public boolean hasEmbeddedField() {
        return embeddedFieldBuilder_ != null || embeddedField_ != null;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      public Embedded getEmbeddedField() {
        if (embeddedFieldBuilder_ == null) {
          return embeddedField_ == null ? Embedded.getDefaultInstance() : embeddedField_;
        } else {
          return embeddedFieldBuilder_.getMessage();
        }
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      public Builder setEmbeddedField(Embedded value) {
        if (embeddedFieldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          embeddedField_ = value;
          onChanged();
        } else {
          embeddedFieldBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      public Builder setEmbeddedField(
          Embedded.Builder builderForValue) {
        if (embeddedFieldBuilder_ == null) {
          embeddedField_ = builderForValue.build();
          onChanged();
        } else {
          embeddedFieldBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      public Builder mergeEmbeddedField(Embedded value) {
        if (embeddedFieldBuilder_ == null) {
          if (embeddedField_ != null) {
            embeddedField_ =
              Embedded.newBuilder(embeddedField_).mergeFrom(value).buildPartial();
          } else {
            embeddedField_ = value;
          }
          onChanged();
        } else {
          embeddedFieldBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      public Builder clearEmbeddedField() {
        if (embeddedFieldBuilder_ == null) {
          embeddedField_ = null;
          onChanged();
        } else {
          embeddedField_ = null;
          embeddedFieldBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      public Embedded.Builder getEmbeddedFieldBuilder() {
        
        onChanged();
        return getEmbeddedFieldFieldBuilder().getBuilder();
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      public EmbeddedOrBuilder getEmbeddedFieldOrBuilder() {
        if (embeddedFieldBuilder_ != null) {
          return embeddedFieldBuilder_.getMessageOrBuilder();
        } else {
          return embeddedField_ == null ?
              Embedded.getDefaultInstance() : embeddedField_;
        }
      }
      /**
       * <code>.ProtocolBuffers.SampleProtoB.Embedded embedded_field = 18;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Embedded, Embedded.Builder, EmbeddedOrBuilder>
          getEmbeddedFieldFieldBuilder() {
        if (embeddedFieldBuilder_ == null) {
          embeddedFieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Embedded, Embedded.Builder, EmbeddedOrBuilder>(
                  getEmbeddedField(),
                  getParentForChildren(),
                  isClean());
          embeddedField_ = null;
        }
        return embeddedFieldBuilder_;
      }

      private com.google.protobuf.MapField<
          String, Integer> mapField_;
      private com.google.protobuf.MapField<String, Integer>
      internalGetMapField() {
        if (mapField_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MapFieldDefaultEntryHolder.defaultEntry);
        }
        return mapField_;
      }
      private com.google.protobuf.MapField<String, Integer>
      internalGetMutableMapField() {
        onChanged();;
        if (mapField_ == null) {
          mapField_ = com.google.protobuf.MapField.newMapField(
              MapFieldDefaultEntryHolder.defaultEntry);
        }
        if (!mapField_.isMutable()) {
          mapField_ = mapField_.copy();
        }
        return mapField_;
      }

      public int getMapFieldCount() {
        return internalGetMapField().getMap().size();
      }
      /**
       * <pre>
       * Map field
       * </pre>
       *
       * <code>map&lt;string, int32&gt; map_field = 19;</code>
       */

      public boolean containsMapField(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetMapField().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMapFieldMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, Integer> getMapField() {
        return getMapFieldMap();
      }
      /**
       * <pre>
       * Map field
       * </pre>
       *
       * <code>map&lt;string, int32&gt; map_field = 19;</code>
       */

      public java.util.Map<String, Integer> getMapFieldMap() {
        return internalGetMapField().getMap();
      }
      /**
       * <pre>
       * Map field
       * </pre>
       *
       * <code>map&lt;string, int32&gt; map_field = 19;</code>
       */

      public int getMapFieldOrDefault(
          String key,
          int defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Integer> map =
            internalGetMapField().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * Map field
       * </pre>
       *
       * <code>map&lt;string, int32&gt; map_field = 19;</code>
       */

      public int getMapFieldOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Integer> map =
            internalGetMapField().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMapField() {
        internalGetMutableMapField().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * Map field
       * </pre>
       *
       * <code>map&lt;string, int32&gt; map_field = 19;</code>
       */

      public Builder removeMapField(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableMapField().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, Integer>
      getMutableMapField() {
        return internalGetMutableMapField().getMutableMap();
      }
      /**
       * <pre>
       * Map field
       * </pre>
       *
       * <code>map&lt;string, int32&gt; map_field = 19;</code>
       */
      public Builder putMapField(
          String key,
          int value) {
        if (key == null) { throw new NullPointerException(); }
        
        internalGetMutableMapField().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * Map field
       * </pre>
       *
       * <code>map&lt;string, int32&gt; map_field = 19;</code>
       */

      public Builder putAllMapField(
          java.util.Map<String, Integer> values) {
        internalGetMutableMapField().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtocolBuffers.SampleProtoB)
    }

    // @@protoc_insertion_point(class_scope:ProtocolBuffers.SampleProtoB)
    private static final SampleProtoB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SampleProtoB();
    }

    public static SampleProtoB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SampleProtoB>
        PARSER = new com.google.protobuf.AbstractParser<SampleProtoB>() {
      @Override
      public SampleProtoB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SampleProtoB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SampleProtoB> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SampleProtoB> getParserForType() {
      return PARSER;
    }

    @Override
    public SampleProtoB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolBuffers_SampleProtoB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtocolBuffers_SampleProtoB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolBuffers_SampleProtoB_Embedded_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtocolBuffers_SampleProtoB_Embedded_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtocolBuffers_SampleProtoB_MapFieldEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtocolBuffers_SampleProtoB_MapFieldEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022SampleProtoB.proto\022\017ProtocolBuffers\"\247\005" +
      "\n\014SampleProtoB\022\024\n\014double_field\030\001 \001(\001\022\023\n\013" +
      "float_field\030\002 \001(\002\022\023\n\013int32_field\030\003 \001(\005\022\023" +
      "\n\013int64_field\030\004 \001(\003\022\024\n\014uint32_field\030\005 \001(" +
      "\r\022\024\n\014uint64_field\030\006 \001(\004\022\024\n\014sint32_field\030" +
      "\007 \001(\021\022\024\n\014sint64_field\030\010 \001(\022\022\025\n\rfixed32_f" +
      "ield\030\t \001(\007\022\025\n\rfixed64_field\030\n \001(\006\022\026\n\016sfi" +
      "xed32_field\030\013 \001(\017\022\026\n\016sfixed64_field\030\014 \001(" +
      "\020\022\022\n\nbool_field\030\r \001(\010\022\024\n\014string_field\030\016 " +
      "\001(\t\022\023\n\013bytes_field\030\017 \001(\014\022C\n\021custom_enum_" +
      "field\030\020 \001(\0162(.ProtocolBuffers.SampleProt" +
      "oB.CustomEnum\022\023\n\013array_field\030\021 \003(\t\022>\n\016em" +
      "bedded_field\030\022 \001(\0132&.ProtocolBuffers.Sam" +
      "pleProtoB.Embedded\022>\n\tmap_field\030\023 \003(\0132+." +
      "ProtocolBuffers.SampleProtoB.MapFieldEnt" +
      "ry\032\030\n\010Embedded\022\014\n\004name\030\001 \001(\t\032/\n\rMapField" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\"(\n" +
      "\nCustomEnum\022\005\n\001A\020\000\022\005\n\001B\020\001\022\005\n\001C\020\003\022\005\n\001D\020\004B" +
      ":\n io.confluent.ksql.serde.protobufB\026Sam" +
      "pleProtoBOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ProtocolBuffers_SampleProtoB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtocolBuffers_SampleProtoB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtocolBuffers_SampleProtoB_descriptor,
        new String[] { "DoubleField", "FloatField", "Int32Field", "Int64Field", "Uint32Field", "Uint64Field", "Sint32Field", "Sint64Field", "Fixed32Field", "Fixed64Field", "Sfixed32Field", "Sfixed64Field", "BoolField", "StringField", "BytesField", "CustomEnumField", "ArrayField", "EmbeddedField", "MapField", });
    internal_static_ProtocolBuffers_SampleProtoB_Embedded_descriptor =
      internal_static_ProtocolBuffers_SampleProtoB_descriptor.getNestedTypes().get(0);
    internal_static_ProtocolBuffers_SampleProtoB_Embedded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtocolBuffers_SampleProtoB_Embedded_descriptor,
        new String[] { "Name", });
    internal_static_ProtocolBuffers_SampleProtoB_MapFieldEntry_descriptor =
      internal_static_ProtocolBuffers_SampleProtoB_descriptor.getNestedTypes().get(1);
    internal_static_ProtocolBuffers_SampleProtoB_MapFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtocolBuffers_SampleProtoB_MapFieldEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
